### ISSUE TITLE
Feature: request a feature by posting an issue

### ISSUE THREAD

**Issue by dominictarr** [dominictarr/feedopensource#1]
users post a feature request by posting and issue that describes what they want to be able to do with the project and why it's a good idea.

Then, a discussion ensues to figure out what that feature really entails and whether it's actually a good idea.

If someone decides to implement a feature, they may post updates to that issue.

In feedopensource an issue represents some unit of work that forms part of an iteration,
feedopensource read's the issues that are part of an active (funded) iteration, and as they close,
it updates the status of that iteration.

**Comment by NHQ** [comment]
Does each "feature" have its own funding goal?

**Comment by dominictarr** [comment]
no. Features are grouped into a Iteration, and the iteration is funded.
This allows for cases where you have related features, like say there are 3 user facing features that all depend on a refactor or some other internal change that outside users will not be aware of.
It allows the developers to say, "sure, if we do this this and that, I'll need to make this change, so this bunch of work should all be together"

see https://bountysource.com for a per-issue funding model.

**Comment by dominictarr** [comment]
this is half way through, most of the data is collected properly

https://feedopensource.com/iteration/dominictarr/feedopensource/1PTAwipYpP63uNrcxfm5FewxRdZyar6ceu

**Comment by eugeneware** [comment]
That kicks butt @dominictar. Well done!

**Comment by eugeneware** [comment]
Is this based programmatically on scraping the github issue with transactions IDs?

**Comment by ralphtheninja** [comment]
Cool!

**Comment by dominictarr** [comment]
@eugeneware it's all in the url. You give it a user, a repo, and a bitcoin address.
it requests the issues for that user/repo, and looks for issues with a link to that wallet
(i.e. the progressbar badge in https://github.com/dominictarr/feedopensource/issues/4)
that makes it a valid iteration.

then it requests the wallet transactions (from blockchain.info) and the comments (from github).
you can get the raw data if you do https://feedopensource.com/iteration/dominictarr/feedopensource/1PTAwipYpP63uNrcxfm5FewxRdZyar6ceu.json

**Comment by dominictarr** [comment]
DONE.
