### ISSUE TITLE
use https for progress bar images

### ISSUE THREAD

**Issue by ghost** [dominictarr/feedopensource#10]
github aggressively caches external images so it can take a while for image updates to go through, but not on https. We use https for testling-ci for this purpose and travis-ci does too.

**Comment by ralphtheninja** [comment]
+1 It's important that the progress bar is accurate.

**Comment by dominictarr** [comment]
Absolutely. This will be a part of the next iteration.

**Comment by dominictarr** [comment]
this is DONE!

**Comment by ralphtheninja** [comment]
Seems there is a problem with the certificate.

**Comment by Raynos** [comment]
Also seeing a problem with the certificate.

**Comment by dominictarr** [comment]
sorry, this is now fixed.

**Comment by dominictarr** [comment]
switched from a free to paid CA
