### ISSUE TITLE
CONTRIBUTING...

### ISSUE THREAD

**Issue by joates** [dominictarr/feedopensource#18]
i am very interested in contributing my own time to help get this project up-and-running (i have the next 30 days availability) i'm a decent javascript & node coder (also PHP, Perl, C++, Java etc etc i'll have a go at anything kind of programmer :) ultimately i would benefit from being able to use this type of platform for my own projects.

**Comment by dominictarr** [comment]
Awesome. okay, I'm starting to work on this now. Can you come find me on IRC #stackvm (on freenode.net) ? lets discuss!

**Comment by joates** [comment]
just fyi..
latest snapshot of my fork is here: https://github.com/joates/feedopensource/tree/dev/it01
will try for regular scheduled PRs (maybe twice a day ?) or as new features/functionality emerge.

also fyi..
i may be a bit "erratic" with my commit schedule, i suffer from migraines (often) and sometimes i'm just not "inspired to code" (sorry if thats too much info) will do my best to keep you informed of progression as it develops (or deteriorates #lol) but still keen to provide support and code up until Feb 10th (then i have to plan ahead for my own project :)

**Comment by dominictarr** [comment]
no problem.
I'm just about to go get breakfast - come find me in irc in a few hours if you are around.
