### ISSUE TITLE
[solution] fatal error: gif_lib.h: No such file or directory (during npm install)

### ISSUE THREAD

**Issue by joates** [dominictarr/feedopensource#25]
if you get this error during npm install of "canvas-progress-bar"..
( which is a dependency of [btcprogress](https://npmjs.org/package/btcprogress) )

`../src/Image.h:20:21: fatal error: gif_lib.h: No such file or directory`

screenshot:
![canvas-progress-bar-fatal-error_screenshot](https://f.cloud.github.com/assets/490654/1917476/61069570-7d99-11e3-8d6f-8f4334a19e16.png)

it's because you are missing the package `libgif-dev`

fix for ubuntu linux is:
`sudo apt-get install libgif-dev`

**Comment by joates** [comment]
i'd guess the mac OSX fix is:
`brew install libgif-dev`

**but i cannot confirm as i am not a mac user.**

anyway closing this as i'm just using it to document the fix/solution so that it is searchable.

**Comment by dominictarr** [comment]
see also [node-canvas](http://ghub.io/canvas)

**Comment by franklinwise** [comment]
brew install giflib

**Comment by acrolink** [comment]
I have managed to solve this issue under openSUSE by:
A. Downloading latest `giflib-devel` `rpm` from:
https://rpmfind.net/linux/rpm2html/search.php?query=giflib-devel
B. Installing it using `zypper install .rpm`

**Comment by mutantkeyboard** [comment]
Sorry to reopen this, but ```apt install libgif-dev``` solves the problem on Debian based systems.
