### ISSUE TITLE
feature: fund an iteration

### ISSUE THREAD

**Issue by dominictarr** [dominictarr/feedopensource#3]
Initially, a project maintainer can create an wallet for an iteration
https://github.com/dominictarr/feedopensource/issues/2
and people who want to support the project can make payments to it.

initially, this will be small scale, so this can probably be just be done using the honour system (i.e. trust the maintainer to return the money if there is not enough to fund the project, etc) but, further down the road (probably sooner rather than later) it will be good to use [bitcoin transaction scripts](https://en.bitcoin.it/wiki/Script) to make this much safer.

Essentially, crowd funding is a form of assurance contract https://en.bitcoin.it/wiki/Contracts#Example_3:_Assurance_contracts

And feedopensource is an series of iterative assurance contracts.
Unfortunately, feature is not currently implemented in the bitcoin UI,
although it is supported in the protocol. 

It will also be necessary to prove that a given github (or whatever)
user is the same as a particular bitcoin wallet (from which a payment to a project is made) this could be easily done by signing a message with that wallet's key ("i am github.com/dominictarr") and then posting that signature to github, in a spot that only that github user can access.

Then, you'll know which github users are responsible for which payments.
(this is important, because the reason the user funds the project is to influence the developer into meeting their needs)

Also making a post on the iteration issue when you fund it is a good idea,
because it will turn up in their follower's newsfeeds, showing their endorsement, and potentially spreading virally.

Using full payments is initially outside the scope of this issue, but down the road, this is how it should be eventually be solved.

**Comment by Raynos** [comment]
When I fund an iteration I want to tweet about it.

Something like:

> I just funded @dominictarr project <name>

Basically if I support a kickstarter project I appreciate announcing that afterwards and sharing it with my twitter followers, I would want to do the same here.

maybe we should provide some kind twitter tweet boilerplate with the project name, developer name & link for other people to fund.

**Comment by dominictarr** [comment]
yes, should definitely encourage users to share the fact that they have supported a project.

**Comment by dominictarr** [comment]
Although, since there isn't a link you click on and you don't have to log in to anything then it's I'm not sure where to put that encouragement.

**Comment by Raynos** [comment]
once you automate the part where I tell you who I am from my github name / bitcoin transaction hash it might be a good place to prompt me after I insert that information.

**Comment by dominictarr** [comment]
I'm gonna declare this done. feedopensource detects which payments are from which users,
(as they claim by posting the transaction id).
This is enough for the time being.
I'm gonna declare this issue DONE.
