### ISSUE TITLE
Donations overshooting iteration target (brainstorming)

### ISSUE THREAD

**Issue by ralphtheninja** [dominictarr/feedopensource#34]
I was thinking that donations that exceeds the target for an iteration could automatically be transferred to a "pool" address for the project/repository as a whole.

For example, say we have a 1 btc target for an iteration and the total donated amount is 1.05 then 0.05 would be transferred to the project and not the iteration. The developer(s) in charge of that address could then distribute these funds as they see fit. Perhaps buying more server space for the project. Or what about transferring the extra funds to the running server (autonomous agent) which in turn buys that server space itself, when needed.

Perhaps this is out of the scope of this project, since this would mean more complicated transactions in the bitcoin protocol, such as multi signature transactions and more advanced transaction logic.

**Comment by dominictarr** [comment]
Well, currently, once you have transferred money to a project, it's theirs to manage as they see fit.
That could include purchasing servers, etc.

Autonomous agent would be interesting, but probably that should be addressed within a large scope of
all the things that could benefit from that feature, as I think that would only be a small aspect of feedopensource.

Although, getting proper assurance contracts working could be cool.

Maybe the most important thing with overshooting is to get new comers to donate next time (instead?).
hmm.... or maybe just putting in a token amount, posting to the iteration issue is enough because then you'll get the emails that github sends out.

**Comment by joates** [comment]
agree with @dominictarr that the _fair-use of funds_ are handled by the wallet owner (dev / stakeholder / project lead, etc), they can always provide feedback (e.g. "thanks for funding, we now have a better server spun-up!"), also it wouldn't be too hard to divide the excess satoshi by the number of funders and refund them all, equally simple to push the excess funds into next iteration or project-wide wallet as @ralphtheninja suggests.

my concern would be other types of funding controls..
i.e. someone decides they want a feature implemented immediately, raises an issue, tasks it and funds it 10btc 100% themselves, that puts the dev in a very awkward position.

in this situation ( _which is somewhat exaggerated to make a point_ ) there is no consensus or even discussion with the community, some minimums and maximums in the iteration config (adjustable by the dev) should keep things fair or at least discourage bad behavior.

> the other question i want to propose is that should a small financial commitment be enforced / encouraged from the individual proposing a task for an iteration?

perhaps just enough to keep things honest (like 0.5% of iteration total) this would be non-refundable and could be considered a contribution towards the ongoing & future costs incurred by the project. It would be fully transparent and appear in the project-wide wallet ( _as previously suggested by_ @ralphtheninja )

**Comment by dominictarr** [comment]
So, currently, only the project collaborators may create a valid iteration - this prevents someone creating one and using a wallet that doesn't actually belong to the project.

Also, authors can always return the money to funders. I don't think it's productive to build stuff to deal with hypotheticals like "abusive funders", better to cross that bridge when we come to it, as the best decision is probably highly dependent on that particular situation.

I think if the maintainers agree/are persuaded it's a good idea then it should be merged. I certainly do not want to discourage people posting issues.

**Comment by joates** [comment]
> I certainly do not want to discourage people posting issues.

+1
that is a very valid point ( _which i hadn't considered_ )
