### ISSUE TITLE
Multiple badge formats?

### ISSUE THREAD

**Issue by Raynos** [dominictarr/feedopensource#35]
Currently the iteration 1 badge looks like

![badge](https://feedopensource.com/iteration/dominictarr/feedopensource/1PTAwipYpP63uNrcxfm5FewxRdZyar6ceu.png#1.2)

https://nodei.co/ has multiple formats

It might be nice to have a larger format for the badge that lists the actual tasks (and their names from the github issues) instead of just showing a check box per task.

**Comment by dominictarr** [comment]
Cool, I can actually make it bigger - that one is 300 wide, but it can also be 600, or 900.
Although, since I've made some aspects relative and some pixels, it starts to look not quite right.

It does work though. some parts just look a few pixels off, which I find annoying.

**Comment by ralphtheninja** [comment]
I really like the look but it would be cool to get some input from designers as well. For instance is the DONE! necessary information when we have COMPLETE as well?

**Comment by dominictarr** [comment]
No, but I wanted to emphasize a "fuck yeah!" sense of achievement.
the DONE could be more awesome though.

**Comment by Raynos** [comment]
I was thinking making it taller and adding the information of all the github issues titles that are related to the iteration in it.

It would make it a big fat image but it would be kind of cool to get an overview of the entire iteration in a single image. The default would be the smaller / leaner one.

I guess I'm not thinking of a badge but more of an informational image.

**Comment by dominictarr** [comment]
how about, if you click the badge at it takes you to a html page that shows all that information?

**Comment by Raynos** [comment]
@dominictarr that would be cool! That's a really good idea :)

**Comment by dominictarr** [comment]
here you go:
[![badge](https://feedopensource.com/iteration/dominictarr/feedopensource/1PTAwipYpP63uNrcxfm5FewxRdZyar6ceu.png#1.2)](https://feedopensource.com/iteration/dominictarr/feedopensource/1PTAwipYpP63uNrcxfm5FewxRdZyar6ceu#1.2)

**Comment by Raynos** [comment]
Nice! Really cool.
