### ISSUE TITLE
feature proposal: a pluggable web services api

### ISSUE THREAD

**Issue by joates** [dominictarr/feedopensource#38]
this was my initial response to [this comment](https://github.com/dominictarr/feedopensource/issues/4#issuecomment-32452044)

> i have some ideas about decoupling the api interface with a layer of abstraction and then promoting an ecosystem of userland plugins to provide the bindings to specific services (github / blockchain / anything else that develops in the future) ~~but feeling a bit under the weather so will think on this and propose something in a new discussion when i'm feeling more lucid~~.

**Open for discussion.**
##### i will add any additional ramblings below as they occur to me..
- Something like this would probably require an entire iteration of it's own. ( _added 17-Jan-2014_ )
- github is great, but as we all know it goes down (rarely.. but it does) ( _added 19-Jan-2014_ )
- integration with emerging altcoins (Lite, Zeta.. dare i mention Doge :)) ( _added 19-Jan-2014_ )

for example: ( _added 19-Jan-2014_ )

> i was contemplating a PR to implement this [304 response](http://developer.github.com/guides/getting-started/#conditional-requests) into the existing micro-caching system, but it feels like a regression to create increased dependency on a single platform in the core system, IMO this should be encapsulated into a plugin so that the core remains portable (in theory) to **any forum-type platform** that has an API we can interact with.

**Comment by dominictarr** [comment]
as it's stated this is too broad, I'm gonna close this issue, since it's covered
by https://github.com/dominictarr/feedopensource/issues/9
