### ISSUE TITLE
Feature: Support for QR codes

### ISSUE THREAD

**Issue by ralphtheninja** [dominictarr/feedopensource#40]
QR codes simplify the payment process a great deal and have more or less become the standard way of conveying bitcoin addresses to smart phones.

**Comment by dominictarr** [comment]
could probably use this module: https://github.com/cryptocoinjs/qr-encode

**Comment by ralphtheninja** [comment]
Any ideas of where this should go? Should it be part of the badge?

**Comment by dominictarr** [comment]
Yeah, probably, otherwise you'd just need two badges.
Okay. Gonna make put this in iteration 2.

**Comment by joates** [comment]
the pattern i've seen more often is to prompt the user to show the code with a link 
e.g. `bitcoin: 18oBEV9hFdDMEct9Ys2bSAuEY4bi2KSMHi` ([show QR Code](https://github.com/dominictarr/feedopensource/issues/40#))

then the actual QR Code image displays in an overlay (i guess because it needs to be big enough to capture and be decoded accurately?)

**Comment by dominictarr** [comment]
we can't put any javascript on github, so an overlay is out, but we could put a QR code on the summary page.

**Comment by ralphtheninja** [comment]
Use http://miohtama.github.io/bitcoinaddress.js on the summary page?

**Comment by dominictarr** [comment]
how big does the QR code need to be? will 100x100 work?
I think I can easily squash the rest of the badge into 200x100 and then use the 300x100 standard size: http://en.wikipedia.org/wiki/Web_banner#Standard_sizes

**Comment by dominictarr** [comment]
okay, I've added a qr code to the iteration page - which the user will see when they click on the badge. Is that obvious enough? or does this definitely need to be in the badge?

**Comment by joates** [comment]
are you sure that is the correct QR code? it's a different image on the wallet (pic)..

![screenshot from 2014-03-06 15 40 01](https://f.cloud.github.com/assets/490654/2346774/c9f71932-a545-11e3-9b95-b9775c4ebb8b.png)

**Comment by joates** [comment]
why not link directly to the img from blockchain.info ?

[View QR Code](https://blockchain.info/qr?data=18oBEV9hFdDMEct9Ys2bSAuEY4bi2KSMHi&size=300)
( _there is a size= parameter_ )

**Comment by dominictarr** [comment]
scan it! it's the same value - it's probably just caused by a different level of error correction or some other parameter like that.

**Comment by dominictarr** [comment]
can anyone comment whether this is good enough or the QR code should be in the badge?

**Comment by ralphtheninja** [comment]
Cramming the QR code in the badge might be too tight. I'm fine with it showing up on the iteration page only.

**Comment by dominictarr** [comment]
okay, I'm gonna mark this as done.
