### ISSUE TITLE
show title of github issue on iteration html page

### ISSUE THREAD

**Issue by Raynos** [dominictarr/feedopensource#41]
Currently it shows an array of sorted tasks as just link (DONE). It would be nice if the text of the `<a>` was the title of the issue.

This would require changing the api to add `{ title }` to `{ html_url, url, closed }` to the `links` array on the `Iteration` model.

**Comment by dominictarr** [comment]
yes.

**Comment by dominictarr** [comment]
I'm not sure when I did it but this is fixed now.
