### ISSUE TITLE
[fixed] bug when repo has a hyphen in it (e.g. test-repo)

### ISSUE THREAD

**Issue by joates** [dominictarr/feedopensource#43]
probably just needs 'escaping' somewhere?

this works -> [project](https://github.com/xtcrypto/project/issues/1)
this doesn't -> [funding-project](https://github.com/xtcrypto/funding-project/issues/1)

**Comment by ralphtheninja** [comment]
I get an error when trying the badges.

**Comment by ralphtheninja** [comment]
Weird. At first I got the same error on both of them:

Error: could not find iteration
    at /var/www/feedopensource/api/index.js:57:8
    at /var/www/feedopensource/api/index.js:41:5
    at next (/var/www/feedopensource/lib/get.js:63:5)
    at process._tickCallback (node.js:415:13)

After that the first works and the second doesn't

**Comment by joates** [comment]
i'm doing some more testing today ( _updated 22-Jan @9am GMT_ )
- when i rename the repo "funding-project" -> "funding_project" ( _with underscore_ ) and change the badge code to match, it works as expected !!
- **hyphen is a valid character in a URL.**
- ~~it must be the shell that is interpreting it (incorrectly).~~ (edit _RegExp didn't test for hyphens_ )

**Comment by dominictarr** [comment]
Okay, I think this is fixed now.

**Comment by dominictarr** [comment]
can you confirm?
