### ISSUE TITLE
What are your thoughts on App.net's new approach to funding feature development?

### ISSUE THREAD

**Issue by colingourlay** [dominictarr/feedopensource#47]
https://backer.app.net/

**Comment by dominictarr** [comment]
This looks interesting. It's different to what feedopensource is trying to be,
but it certainly allows users of a pay-for service to give more meaningful feedback, and so I'm definitely in favor of that. In this case, the money isn't really about paying for the service, but really just to make the survey meaningful. If you had a regular survey, people can vote with fake emails, etc, but to submit fake "votes" here is just too expensive.

I don't think it's the right way to fund opensource, and I've already explained that opinion in blog posts, but it is nice that they are doing that for free.
