### ISSUE TITLE
Badge does not indicate the target

### ISSUE THREAD

**Issue by jhs** [dominictarr/feedopensource#48]
I just funded iteration two; but I was confused because I had no idea what your target was. Now that it is partially, funded, I can divide the pledges by the percentage of completion and get your target (looks like 1.25 BTC) but it would have been nice to see that from the start. That way I might have chosen an amount which covers a desired fraction of the target (say, 25% or 0.3125 BTC). I know that is irrational--I should pay what it's "worth" to me--but hey we are talking about pricing signals here, not rationality.

**Comment by dominictarr** [comment]
this is a good point. I'm adding this to iteration2.

**Comment by dominictarr** [comment]
okay, I fixed this:

https://feedopensource.com/iteration/dominictarr/feedopensource/18oBEV9hFdDMEct9Ys2bSAuEY4bi2KSMHi.png

It shows it as `sum(/target) percent %`.
Is that sufficiently obvious?

**Comment by dominictarr** [comment]
closing this.
