### ISSUE TITLE
Iteration 2 web page says 0% funded in text

### ISSUE THREAD

**Issue by Raynos** [dominictarr/feedopensource#49]
It says 33% funded in the badge.

https://feedopensource.com/iteration/dominictarr/feedopensource/18oBEV9hFdDMEct9Ys2bSAuEY4bi2KSMHi

It looks like the `0% funded` in the `Funders (0.4000btc, 0% funded)` requires updating.

It also shows an 0 **unclaimed** grumpy cat. Maybe hide the grumpy cat if hes grumpy about 0btc

**Comment by dominictarr** [comment]
will append this to iteration2.

**Comment by dominictarr** [comment]
this is fixed.
