### ISSUE TITLE
Feature:  multiple concurrent iterations

### ISSUE THREAD

**Issue by NHQ** [dominictarr/feedopensource#8]
Speed up a project, tackle different domains at the same time, and feed more open sourcerers!

Iterations might then should have ID's that are not sequential.

**Comment by dominictarr** [comment]
This might add "management" overhead to a project. With multiple teams working at once, you'd need to be decoupled. This may not be straightforward, depending on the project - you could just refactor out part of the project. For example, bitcoin and bitcoin-qt could be considered as separate projects. Or a database, and a database administration panel.

However, lets leave this on the table and see if it comes up in practice.

**Comment by dominictarr** [comment]
since feedopensource imposes very little structure, there is nothing stopping you from doing this, if you so see fit to do it.

Closing.
